AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
