AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRailsVersion: 5.1
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
