language: ruby

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphviz

env:
  - DATABASE_SOCKET=

install:
  - bundle install --jobs=3 --retry=3
  - nvm install
  - yarn install

before_script:
  - bin/rails db:setup

script:
  - bin/rails test
  - yarn lint

notifications:
  email: false
