language: ruby

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

install:
  - bundle install --jobs=3 --retry=3
  - nvm install
  - yarn install

script:
  - bundle exec rails test
  - yarn lint

notifications:
  email: false
