language: ruby

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphviz
  chrome: stable

env:
  - DATABASE_SOCKET=

before_install:
  - bundle config --local build.nokogiri --use-system-libraries
  - nvm install
  - yarn install

before_script:
  - bundle exec rails db:setup
  - bundle exec chromedriver-update

script:
  - bundle exec rails test
  - bundle exec rails test:system
  - yarn lint

branches:
  only:
    - master

# deploy:
#   provider: script
#   script: rvm . do ./.travis/deploy.sh
#   skip_cleanup: true
#   on:
#     branch: master

notifications:
  email: false
