language: ruby

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphviz

env:
  - DATABASE_SOCKET=

before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - bundle config --local build.nokogiri --use-system-libraries
  - nvm install
  - yarn install

before_script:
  - bundle exec rails db:setup

script:
  - bundle exec rails test
  - yarn lint

deploy:
  provider: script
  script: rvm . do ./.travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
