language: ruby

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphviz

install:
  - bundle install --jobs=3 --retry=3
  - nvm install
  - yarn install

script:
  - bundle exec rails test
  - yarn lint

deploy:
  provider: script
  script: rvm . do .travis/deploy.sh
  on:
    branch: master

notifications:
  email: false
